### ISSUE TITLE
Matchbox with terraform/bootkube-install fails to bring up etcd3

### ISSUE THREAD

**Issue by pfischer8989** [coreos/matchbox#624] opened 2017-07-31 19:32 UTC
This is the command runs to bring up etcd3 and it just hangs. I put in the debug line to see what is going on and it seems to hang fetching the etcd 3 image from quay. So I fetched it manually but it did not seem to make a diff. 

No image gets spawn with rkt so you cannot see anything.....It simply hangs and the install process stops. 

The coreOS part works well and the OS installs fine. 

cnfc5cnfi01 ~ # /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=systemd-dir,target=/run/systemd/system --volume systemd-dir,kind=host,source=/run/systemd/system,readOnly=true --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --volume data-dir,kind=host,source=/var/lib/etcd,readOnly=false --volume etc-ssl-certs,kind=host,source=/etc/ssl/etcd,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=data-dir,target=/var/lib/etcd --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci --debug quay.io/coreos/etcd:v3.2.0 --user=232 --
image: using image from file /usr/lib64/rkt/stage1-images/stage1-fly.aci
image: searching for app image quay.io/coreos/etcd

cnfc5cnfi01 ~ # rkt image list
ID			NAME					SIZE	IMPORT TIME	LAST USED
sha512-84889bd10510	coreos.com/etcd:v3.2.0			63MiB	4 days ago	4 days ago
sha512-fa9bf3e4e7bf	coreos.com/rkt/stage1-fly:1.25.0	17MiB	26 minutes ago	26 minutes ago

**Comment by dghubble** [comment] 2017-07-31 20:22
A rkt fetch issue like that hints at an issue with the host's DNS resolution. Can you dig quay and pull and fetch the image ok manually?

You didn't mention much about your environment or network setup. QEMU/KVM or physical hardware? Upstream DNS server correct? See #437 - there were similar resolution issues (though later on in bootstrapping) in out-of-box default openstack or virtualbox environments.

**Comment by pfischer8989** [comment] 2017-07-31 20:29
Yes DNS seems to be working properly. I can resolve quay and that is how i pulled down the image manually in the first place with rkt fetch from the command line. If it is there already why would it try to search quay and pull the image again? I have noticed some issues with the internet that the servers are connected too. 

My environment is bare metal. I have DHCP/PXE/DNS/Matchbox all setup again i am using terraform and the bootkube example to install a master node and three worker nodes. The OS installs fine but on the master it seems to die on getting etcd3 installed. It worked on an older version but i think it was etcd2 which does not use rkt.

**Comment by dghubble** [comment] 2017-07-31 21:01
Using the Terraform-based `bootkube-install` examples (default to on-host etcd), before TLS secrets have been transferred, you'll see:

```
Jul 31 20:51:56 node1.example.com etcd-wrapper[1020]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=systemd-dir,target=/run/systemd/system --volume systemd-dir,kind=host,source=/run/systemd/system,readOnly=true --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --volume data-dir,kind=host,source=/var/lib/etcd,readOnly=false --volume etc-ssl-certs,kind=host,source=/etc/ssl/etcd,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=data-dir,target=/var/lib/etcd --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/etcd:v3.2.0 --user=232 --
Jul 31 20:51:57 node1.example.com etcd-wrapper[1020]: run: stat of host path /etc/ssl/etcd: stat /etc/ssl/etcd: no such file or directory
Jul 31 20:51:57 node1.example.com systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
```

and after TLS assets are present, it should start.

```
$ journalctl -u etcd-member -f
Jul 31 20:54:52 node1.example.com etcd-wrapper[1547]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=systemd-dir,target=/run/systemd/sys$
em --volume systemd-dir,kind=host,source=/run/systemd/system,readOnly=true --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/syst$
md/notify --volume data-dir,kind=host,source=/var/lib/etcd,readOnly=false --volume etc-ssl-certs,kind=host,source=/etc/ssl/etcd,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates$
readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=data-dir,target=/var/lib/etcd --mount volume=etc-ssl$
certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-f$
om-dir=stage1-fly.aci quay.io/coreos/etcd:v3.2.0 --user=232 --
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.371686 I | pkg/flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://node1.example.com:2379
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.372017 I | pkg/flags: recognized and used environment variable ETCD_CERT_FILE=/etc/ssl/certs/etcd/server.crt
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.372157 I | pkg/flags: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=true
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.372418 I | pkg/flags: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.372641 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://node1.example.com:2380
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.373599 I | pkg/flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=node1=https://node1.example.com:2380
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.373735 I | pkg/flags: recognized and used environment variable ETCD_KEY_FILE=/etc/ssl/certs/etcd/server.key
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.373850 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.373980 I | pkg/flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374096 I | pkg/flags: recognized and used environment variable ETCD_NAME=node1
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374204 I | pkg/flags: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/ssl/certs/etcd/peer.crt
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374318 I | pkg/flags: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=true
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374426 I | pkg/flags: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/ssl/certs/etcd/peer.key
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374533 I | pkg/flags: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/certs/etcd/peer-ca.crt
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374682 I | pkg/flags: recognized and used environment variable ETCD_STRICT_RECONFIG_CHECK=true
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.374903 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/ssl/certs/etcd/server-ca.crt
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375104 W | pkg/flags: unrecognized environment variable ETCD_SSL_DIR=/etc/ssl/etcd
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375282 W | pkg/flags: unrecognized environment variable ETCD_USER=etcd
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375551 W | pkg/flags: unrecognized environment variable ETCD_IMAGE_TAG=v3.2.0
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375820 I | etcdmain: etcd Version: 3.2.0
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375831 I | etcdmain: Git SHA: 66722b1
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375836 I | etcdmain: Go Version: go1.8.3
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375841 I | etcdmain: Go OS/Arch: linux/amd64
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375846 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.375925 I | embed: peerTLS: cert = /etc/ssl/certs/etcd/peer.crt, key = /etc/ssl/certs/etcd/peer.key, ca = , trusted-ca = /etc/ssl/certs/et
cd/peer-ca.crt, client-cert-auth = true
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.377901 I | embed: listening for peers on https://0.0.0.0:2380
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.378682 I | embed: listening for client requests on 0.0.0.0:2379
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.393385 I | pkg/netutil: resolving node1.example.com:2380 to 172.18.0.21:2380
Jul 31 20:54:54 node1.example.com etcd-wrapper[1547]: 2017-07-31 20:54:54.396625 I | pkg/netutil: resolving node1.example.com:2380 to 172.18.0.21:2380
```

I can't reproduce your issue myself or in the test environment.

Can you list:

* Container Linux version
* Repo SHA hash used in the module reference:

```
module "mycluster" {
  source = "git::https://github.com/coreos/matchbox.git//examples/terraform/modules/bootkube?ref=SOME_SHA_HASH"
```

**Comment by dghubble** [comment] 2017-07-31 21:03
Also, etcd2 hasn't been used since Kubernetes 1.5, which I believe predates my Terraform-based examples.

**Comment by pfischer8989** [comment] 2017-07-31 21:51
Hmm ok so there is no /etc/ssl/etcd directory.....hmm probably why it does not start up properly. I assume this is done through the ssh.tf module. I had to edit this file to get the ssh to even work or it hangs when trying to ssh into the machines once the OS is installed. Had to add the location of my private key so it could login. 

I will dig through the logs or will probably bootstrap it again and see if i can find out why those files are not being copied over......

My container linux version is:

container_linux_version = "1409.7.0"
container_linux_channel = "stable"

This is what i have in my cluster.tf.....which i think is default.

module "cluster" {
  source = "../modules/bootkube"

**Comment by pfischer8989** [comment] 2017-07-31 22:15
Yeah so re-ran the installer and found this in the terraform debug log...

root@cnfclbutil01:~/matchbox/examples/terraform/bootkube-install# cat terraform.log | grep TLS
2017/07/31 21:56:12 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/07/31 21:56:12 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=linux&signature=9b94ceb6-3470-2293-3a73-169a8ff9594a&version=0.9.6: net/http: TLS handshake timeout
2017/07/31 21:56:12 [DEBUG] plugin: terraform: tls-provider (internal) 2017/07/31 21:56:12 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=linux&signature=9b94ceb6-3470-2293-3a73-169a8ff9594a&version=0.9.6: net/http: TLS handshake timeout
2017/07/31 21:56:12 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=linux&signature=9b94ceb6-3470-2293-3a73-169a8ff9594a&version=0.9.6: net/http: TLS handshake timeout
2017/07/31 21:56:12 [DEBUG] plugin: terraform: file-provisioner (internal) 2017/07/31 21:56:12 [ERR] Checkpoint error: Get https://checkpoint-api.hashicorp.com/v1/check/terraform?arch=amd64&os=linux&signature=9b94ceb6-3470-2293-3a73-169a8ff9594a&version=0.9.6: net/http: TLS handshake timeout

Seems I am having some connectivity issues.....

**Comment by dghubble** [comment] 2017-07-31 22:19
> Had to add the location of my private key

Ah, you should be able to add your key to your `ssh-agent` via [github docs](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-ssh-key-to-the-ssh-agent). That's my fault if its not documented well enough, with a yubikey for ssh it "just works" like that already.

> This is what i have in my cluster.tf

Yep, that's perfectly fine if you're checking out the matchbox repo and defining your cluster there. Over time, it can be handy to have your own Git repo with your infrastructure declared in it (lots of clusters) and you'd swap the relative file path for a git source, which has the advantage of referencing a specific hash. So in your case, what's the most recent `git log` in your checkout of matchbox?

> there is no /etc/ssl/etcd directory

Yeah, assets are added to each controller via the ssh.tf step.  https://github.com/coreos/matchbox/blob/master/examples/terraform/modules/bootkube/ssh.tf#L54. If you're interested, it should be identical to what's happening manually in the non-terraform docs. Shown here https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md#bootkube. If its causing issues, during debugging you might remove the ssh.tf file and copy the assets yourself to see if that works. Or ask for more debug logs from terraform

**Comment by pfischer8989** [comment] 2017-08-01 01:19
Ha yeah the ssh keys took a bit to figure that one out when I encountered it.  It probably should be documented....and I documented it on my blog so I would not forget myself =o)

If my internet access is not fixed this week I will copy things over manually to get it working. I know it is expected that you have internet access when doing installs like this but in large telco/enterprise environments it is not always the case. Wish I had known how dependant it was on the internet service before i started it would have saved me some time....live and learn i guess =o)

Thanks for all your help.....

**Comment by dghubble** [comment] 2017-08-01 23:14
I'm confused. I thought you were able to rkt fetch the image manually so you had outbound access to quay?

Yes, these Kubernetes cluster examples pull Docker images from quay.io and a few ACIs too. Container Linux also checks for OS updates periodically. There are enterprise products for hosting a docker registry internally or running a CoreUpdate server internally. They're not something I can put in these open-source examples however.

If you're quite motivated, you might look at my [demo](https://github.com/coreos/matchbox/tree/demo) branch I used for an offline cluster provisioning demo or look into running a [squid-proxy](https://github.com/coreos/matchbox/tree/master/contrib/squid) (unofficial docs).

**Comment by pfischer8989** [comment] 2017-08-02 14:49
So here was the issue....i basically had some flakey internet service. These servers are plugged into a a large lab network which was going through some config changes itself. This led my connection to be a bit unstable. It worked sometimes and other times it would time out. 

Anyway talked to the network ops guys and fixed the issue.....after that the install worked fine. I have a working bare-metal cluster on three boxes with kubernetes

Thanks for the links on the demo branch i will have a look.

Thanks for all your help!!

**Comment by dghubble** [comment] 2017-08-02 16:01
Hooray! Thanks for following up

**Closed by dghubble** 2017-08-02 16:01 UTC
