### ISSUE TITLE
Kubelet Upgrade - Upgrading self-hosted Kubernetes 

### ISSUE THREAD

**Issue by andrewwebber** [coreos/matchbox#588] opened 2017-06-24 15:31 UTC
I was not able to follow the documentation on upgrading kubelets.
In Container Linux the kubelet is a wrapper rkt container not listed within the kube-system namespace as documented.

**Comment by dghubble** [comment] 2017-06-24 15:50
Yes, self-hosted clusters can be deployed with the kubelet on-host or as Kubernetes pods. When bootkube came on the scene, Container Linux clusters started using the kubelet as a pod concept (and those docs were written), but since then some issues have been found and the feature marked as experimental https://github.com/kubernetes-incubator/bootkube/blob/v0.4.5/cmd/bootkube/render.go#L73

In the Matchbox reference clusters and in Tectonic's enterprise clusters, we've reverted back to kubelet.service running on the host. To complete the rolling upgrade, you'll have to SSH to each node, bump the hyperkube version in the EnvironmentFile, and restart the kubelet. You can see where this EnvironmentFile is written in https://github.com/coreos/matchbox/blob/master/examples/ignition/bootkube-controller.yaml#L132

We know its not as nice as being able to completely do the upgrade via `kubectl`, but the kubelet as a pod is missing some functionality, which was ultimately more important. Hope that helps.

**Comment by andrewwebber** [comment] 2017-06-24 16:07
@dghubble Thanks for the amazing last response.
Does this mean that the documentation needs to be corrected?

**Comment by dghubble** [comment] 2017-06-24 19:07
Yes please, [bootkube-upgrades.md](https://github.com/coreos/matchbox/blob/master/Documentation/bootkube-upgrades.md) hasn't been updated in a while. Switching the subsection on the Kubelet to show that the version must be manually bumped would be appreciated.

**Comment by andrewwebber** [comment] 2017-06-24 20:31
@dghubble As a side note, isnt running kubelet as a daemonset the only logical path to running multi tenant control planes on the same hardware?

**Comment by dghubble** [comment] 2017-06-24 23:26
Perhaps, but lots of additional features would be needed to safely offer multi-tenancy on Kubernetes. The lack of network isolation and host network / port conflicts if you try to run multiple control planes are the first that come to mind. Probably a better discussion to take to upstream Kubernetes, its not an explicit goal of the self-hosted architecture.

**Comment by dghubble** [comment] 2017-06-26 23:16
Also, the docs can use rolling updates for the daemonset parts now https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/

**Comment by andrewwebber** [comment] 2017-06-30 10:16
@dghubble In addition, as the "/etc/kubernetes/kubelet.env" file is defined and deployed with ignition, any changes to this file are overridden by ignition on reboot. This means if you change the file and restart the kubelet service you get "1.7.0" but on reboot you get "1.6.6".
I have not found a way to change the ignition config for a coreos machine after a "install-reboot".

**Comment by andrewwebber** [comment] 2017-06-30 11:07
@dghubble I have completely misunderstood ignition and read that it only runs once and not every reboot. So i guess across a cluster another tool would be needed to upgrade all nodes disk contents

**Comment by dghubble** [comment] 2017-06-30 18:39
Yes, Ignition was designed to provision the disk once, on the first disk boot (or on PXE boots if first_boot=true arg is set). It will not run again and override changes, unlike cloud-config. Ignition is part of an immutable infrastructure shift where we try to provision clusters with little on-disk configuration (which would need to be managed) - preferring instead to manage clusters of relatively "dumb" nodes as a whole.

Self-hosted Kubernetes has come a long way in moving control plane components, flannel, and soon etcd components into pods and off the host, so now only the kubelet remains on disk. For you, that means you can either use the experimental self-hosted kubelet or edit that file (*through some means*) on each host when you wish to update the kubelet.

In Tectonic clusters, there is a daemonset service which edits the file for users when they push the "update" button as part of a coordinated cluster upgrade process. I don't include that in Matchbox example clusters because its a closed-source / non-free component of Tectonic clusters and it requires a license too so I couldn't include it if I wanted to.

Matchbox example clusters should contain open-source components only. For now, your best bet is to edit `/etc/kubernetes/kubelet.env` (e.g. SSH, systemd unit pulls the version from somewhere, etc.). Its not in the scope of matchbox to write that version bumping operator, but if a free one were available it could be included.

**Closed by dghubble** 2017-06-30 18:39 UTC

**Comment by andrewwebber** [comment] 2017-06-30 21:25
@dghubble This is such as high quality answer, thank you
